export const LOADING = "AUTH/LOADING";
export const FAILURE = "AUTH/FAILURE";

export const REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "AUTH/RESET_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_SUCCESS = "AUTH/UPDATE_PASSWORD_SUCCESS";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";
