export const LOADING = "BOOTCAMPS/LOADING";
export const FAILURE = "BOOTCAMPS/FAILURE";

export const GET_BOOTCAMPS_SUCCESS = "BOOTCAMPS/GET_BOOTCAMPS_SUCCESS";
export const CURRENT_PAGE = "BOOTCAMPS/CURRENT_PAGE";
export const TOTAL_ITEM_COUNT = "BOOTCAMPS/TOTAL_ITEM_COUNT";
